[package]
name = "rust_mcp_server_9"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libsql = "0.9.23"
tokio = { version = "1", features = ["full"] }

